---
title: "HED"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
# read csv file to tibble
hed_df <- read_csv("human-edit-dist.csv")
hed_df
```

```{r}
# string to tibble with a column of characters
str_to_tibble <- function(str) {
  str_split(str, "") %>% 
    unlist() %>% 
    tibble(char = .)
}
```

```{r}
str_to_tibble(hed_df$seg1[1])
```

```{r}
# function splitting string using this regex: "([^\d\W]+\s*|\d+\s*|[^\w\s]+\s*)" and returning array
str_to_array <- function(str) {
  str_extract_all(str, "[^\\d\\W]+\\s*|\\d+\\s*|[^\\w\\s]+\\s*") %>% 
    unlist()
}
```

```{r}
str_to_array(hed_df$seg1[1])
```

```{r}
longest_common_subsequence <- function(lst1, lst2) {
  m <- length(lst1)
  n <- length(lst2)
  jh <- matrix(0, nrow = m + 1, ncol = n + 1)
  
  for (i in 1:m) {
    for (j in 1:n) {
      if (lst1[i] == lst2[j]) {
        jh[i+1,j+1] <- 1 + jh[i,j]
      } else {
        jh[i+1,j+1] <- max(jh[i,j+1], jh[i+1,j])
      }
    }
  }
  
  result <- c()
  i <- m
  j <- n
  while (i > 0 && j > 0) {
    if (lst1[i] == lst2[j]) {
      result <- c(result, lst1[i])
      i <- i - 1
      j <- j - 1
    } else if (jh[i,j+1] > jh[i+1,j]) {
      i <- i - 1
    } else {
      j <- j - 1
    }
  }
  
  return(rev(result))
}
```


```{r}
all_common_subsequences <- function(lst1, lst2) {
  m <- length(lst1)
  n <- length(lst2)
  jh <- matrix(0, nrow = m + 1, ncol = n + 1)
  result <- c()
  cur_seq <- c()
  
  for (i in 1:m) {
    for (j in 1:n) {
      if (lst1[i] == lst2[j]) {
        jh[i+1,j+1] <- 1 + jh[i,j]
      } else {
        jh[i+1,j+1] <- max(jh[i,j+1], jh[i+1,j])
      }
    }
  }
  
  i <- m
  j <- n
  while (i > 0 && j > 0) {
    if (lst1[i] == lst2[j]) {
      result <- c(result, lst1[i])
      i <- i - 1
      j <- j - 1
    } else if (jh[i,j+1] > jh[i+1,j]) {
      i <- i - 1
    } else {
      j <- j - 1
    }
  }
  
  return(rev(result))
}
```

```{r}
longest_common_subsequence(str_to_tibble(hed_df$seg1[1])$char, 
                           str_to_tibble(hed_df$seg2[1])$char)
```

